python3.7 main.py < tests/test0.txt
python3.7 main.py < tests/test1.txt
python3.7 main.py < tests/test2.txt
python3.7 main.py < tests/test3.txt
python3.7 main.py < tests/test4.txt
python3.7 main.py < tests/test5.txt
python3.7 main.py < tests/test6.txt
python3.7 main.py < tests/test7.txt
python3.7 main.py < tests/test8.txt
python3.7 main.py < tests/test9.txt
python3.7 main.py < tests/test10.txt
python3.7 main.py < tests/test11.txt
python3.7 main.py < tests/test12.txt
python3.7 main.py < tests/test13.txt
python3.7 main.py < tests/test14.txt
python3.7 main.py < tests/test15.txt
python3.7 main.py < tests/test16.txt
python3.7 main.py < tests/test17.txt
python3.7 main.py < tests/test18.txt
python3.7 main.py < tests/test19.txt
python3.7 main.py < tests/test20.txt
python3.7 main.py < tests/test21.txt
